### ISSUE TITLE
JBP Quotes - Hide on page

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#62]
Client Request: We will not have the JBP Quotes ready for launch. Can we hide these sections on the page?

![Screen Shot 2019-09-04 at 5 28 04 PM](https://user-images.githubusercontent.com/48070399/64302706-6240a500-cf39-11e9-86a8-e577aedb3aa8.png)

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by JenStewart1** [comment]
Can you also remove on the JB Bio page?
http://jbpoindexterco.wpengine.com/john-b-poindexter

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by JenStewart1** [comment]
@cmoosman1 still seeing
![Screen Shot 2019-09-05 at 4 34 20 PM](https://user-images.githubusercontent.com/48070399/64390796-181ff800-cffb-11e9-822b-df7def47df68.png)

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build
