### ISSUE TITLE
Footer - remove boxes

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/JBP#70]
http://jbpoindexterco.wpengine.com/contact-us

![image](https://user-images.githubusercontent.com/46331985/64884659-1cf63480-d617-11e9-8416-e44edccb05e9.png)

please remove the boxes that are present in the footer

Thanks!

**Comment by JenStewart1** [comment]
@pguevara65 can you please confirm if this is still happening? I think it's a PC issue.

**Comment by pguevara65** [comment]
Yep still there after a hard refresh.

![image](https://user-images.githubusercontent.com/46331985/66961700-14cd5280-f024-11e9-8faf-110413e5eec5.png)

@JenStewart1

**Comment by JenStewart1** [comment]
Got it. Can you list what browsers? @cmoosman1 can you fix at some point before we launch?

**Comment by pguevara65** [comment]
@JenStewart1 @cmoosman1 I only have Chrome and IE. IF you want to download the others (Safari/Firefox) I can.

IE is a different issue that I'll report but can't confirm if it's an issue there or not since I can't get past the loading screen

**Comment by JenStewart1** [comment]
@cmoosman1 Still seeing on Chrome, IE and Edge. Is this fixable for launch?

Chrome - Version 80.0.3987.149
Edge - Microsoft Edge 44.18362.449.0
IE 11

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build.

**Comment by JenStewart1** [comment]
@cmoosman1 still happening on chrome. there is one box next to "our companies"

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved
